name: plotenv
channels:
  - bioconda
  - conda-forge
dependencies:
  - conda-forge::pandas=2.2.2
  - conda-forge::numpy=1.26.4
  - conda-forge::matplotlib=3.9.0
  - conda-forge::zstandard
  - conda-forge::pretty_html_table=0.9.16
  - conda-forge::seaborn=0.13.2
  - conda-forge::plotly=5.22.0
  - pip
  - pip:
      - Jinja2







